//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeOff
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> timeType_id { get; set; }
        public string reason { get; set; }
        public Nullable<bool> payVacation { get; set; }
        public Nullable<bool> approved { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.TimeSpan> workDayBegin { get; set; }
        public Nullable<System.TimeSpan> workDayEnd { get; set; }
        public Nullable<System.TimeSpan> dinnerBegin { get; set; }
        public Nullable<int> month_id { get; set; }
    
        public virtual timeType timeType { get; set; }
        public virtual Users Users { get; set; }
    }
}
